name: Publish Documentation

on:
  push:
    branches: [ main ]

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install jazzy
      run: gem install jazzy
    - name: Generate documentation
      run: |
        jazzy \
        --clean \
        --source-host-files-url "https://github.com/${GITHUB_REPOSITORY}/tree/${GITHUB_REF}" \
        --module-version "${{ github.event.release.tag_name }}" \
        --copyright "Â© $(date '+%Y') Dave Abrahams. (Last updated: $(date '+%Y-%m-%d'))" \
        --config .jazzy.yml
    - name: Commit docs
      run: |
        git config --local user.email "bot@github.com"
        git config --local user.name "GitHub Actions"
        git fetch origin generated-docs-${GITHUB_REF}
        git checkout --detach origin/generated-docs-${GITHUB_REF}
        rm -rf ./docs
        mv ./.generated-docs docs
        git add ./docs
        git commit -m "Update docs"
        git push origin HEAD:generated-docs-${GITHUB_REF}
